Add pre-run version checks
Addresses #1, #2.

diff --git a/qcr b/qcr
--- a/qcr
+++ b/qcr
@@ -2,14 +2,43 @@
 #
 # A light wrapper for using QCR tools. This is deliberately light, so that
 # users should never have to update this script once they have it, but will
-# always have access to the latest templates.
+# always have access to the latest tools.
 #
-# Please see https://github.com/qcr/tools for full details on how things work,
-# and instructions on how to add your own templates. The more templates the
-# merrier!
+# It is also designed to work offline, and prompt you when updates are
+# available. Please see https://github.com/qcr/tools for full details on how
+# things work.
 #
 # Author: Ben Talbot
-# Version: 0.3.0
+# Version: 0.4.0
+
+set -euo pipefail
+
+INSTALL_DIR="/var/tmp/"
+REPO_DIR="${INSTALL_DIR}qcr"
+
+WARN='\033[0;33m'
+NC='\033[0m'
+
+# Install if not installed
+if [ ! -d "$REPO_DIR" ]; then
+  echo "INSTALLING"
+fi
+
+# Check whether installed version is the latest (flagging if there are updates
+# available, or update check failed)
+latest="1"
+installed=""
+if [ -z "$latest" ]; then
+  printf "${WARN}%s${NC}\n" \
+    "WARN: Check for latest tools failed; using cached version in '$REPO_DIR'"
+elif [ "$latest" != "$installed" ]; then
+  printf "${WARN}%s\n%s${NC}\n" \
+    "WARN: Old version (${installed}) of tools found in '$REPO_DIR'" \
+    "(update to version ${latest} using COMMAND)"
+fi
+exit 0
+
+# Process the requested command
 
 if [[ "$(curl -w "%{url_effective}\n" -I -L -s -S google.com -o /dev/null)" =~ ^http://ias.qut.edu.au* ]]; then
   printf "\e[31m%s\n%s\e[0m" \
