Fixed ssh github check

diff --git a/qcr_standalone b/qcr_standalone
--- a/qcr_standalone
+++ b/qcr_standalone
@@ -11,7 +11,7 @@
 # Author: Ben Talbot
 # Version: 0.5.0
 
-set -euo pipefail
+set -uo pipefail
 
 INSTALL_DIR="/var/tmp"
 REPO_DIR="${INSTALL_DIR}/qcr"
@@ -20,25 +20,6 @@ REPO_CLONE_URL="git@github.com:qcr/tools"
 INFO='\033[0;35m[INFO] '
 ERROR='\033[0;31m[ERROR] '
 NC='\033[0m'
-
-# Function
-function check_for_github_ssh_access() {
-    # Attempt to SSH to GitHub
-    ssh -T git@github.com &>/dev/null
-    RET=$?
-    if [ $RET == 1 ]; then
-        # user is authenticated, but fails to open a shell with GitHub
-        printf "${INFO}User authenticated with GitHub via SSH\n"
-        return 0
-    elif [ $RET == 255 ]; then
-        # user is not authenticated
-        printf "${ERROR}Unable to authenticate with GitHub via SSH.\nPlease make sure you have generated a SSH key on this computer and connected it with your GitHub account.\nSee https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.\n"
-        exit 1
-    else
-        printf "${ERROR}Unknown exit code in attempt to ssh into git@github.com\n"
-        exit 2
-    fi
-}
 
 # Bail if git isn't found
 command -v git >& /dev/null || {
@@ -49,13 +30,25 @@ command -v git >& /dev/null || {
 # Install if not installed
 if [ ! -d "$REPO_DIR" ]; then
   # Check SSH key exists
-  check_for_github_ssh_access
+    ssh -T git@github.com &>/dev/null
+    RET=$?
+    if [ $RET == 1 ]; then
+        # user is authenticated, but fails to open a shell with GitHub
+        printf "${INFO}${NC}User authenticated with GitHub via SSH\n"
+    elif [ $RET == 255 ]; then
+        # user is not authenticated
+        printf "${ERROR}${NC}Unable to authenticate with GitHub via SSH.\nPlease make sure you have generated a SSH key on this computer and connected it with your GitHub account.\nSee https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.\n"
+        exit 1
+    else
+        printf "${ERROR}${NC}Unknown exit code in attempt to ssh into git@github.com\n"
+        exit 2
+    fi
 
   # Install
-  printf "${INFO}%s${NC}\n" \
+  printf "${INFO}${NC}%s\n" \
     "No cached version found. Installing to '$REPO_DIR'..."
   if ! git clone "$REPO_CLONE_URL" "$REPO_DIR"; then
-    printf "${ERROR}%s${NC}\n" \
+    printf "${ERROR}${NC}%s\n" \
       "Install failed, please ensure machine has Internet access."
     exit 1
   fi
